// Code generated by gen/genmethods.go; DO NOT EDIT.

package pkg

import "fmt"

// PrintType 型情報を標準出力する
func (s StructA) PrintType() {
	fmt.Printf("%T\n", s)
}

// PrintType 型情報を標準出力する
func (s structB) PrintType() {
	fmt.Printf("%T\n", s)
}
